### PR TITLE
Added code to work on Power systems

### PR DESCRIPTION
**Pull request by genisysram**
Thanks for the code, its working good.
## What do these changes do?
Added Architecture "ppc64le"
## Are there changes in behavior for the user?
No

### CODE REVIEW

**Comment by clokep** [comment]
I'm not sure this is really necessary unless there's a particular reason to think any of this code *wouldn't* work on a different architecture?

**Comment by genisysram** [comment]
Hi
Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing. 
For more info please contact @gerrith3

**Comment by gerrith3** [comment]
So, the funny thing with python is that it is platform independent until, well, it isn't.  ;)  One of the issues is that some of the older versions of python are not available on Power.  Another is that some python authors have managed to try to run system executables or pull down images off the web or via libraries/modules that use executables built for Intel.  This kind of testing catches that immediately rather than when a user/customer trips over it.  With any luck, they make it to my team and we try to patch things up.  But now we are trying to be a bit proactive since we have completed the addition of Power hardware to Travis CI and updating all projects which use the Intel Travis CI to also build on Power.  Sometimes it is just a belt-and-suspenders approach, but more often we do, over time, catch issues.

**Comment by clokep** [comment]
It doesn't seem that Celery itself gets tested on this architecture though so I'm unsure of the value of adding this.

From your use-case, it seems like there also isn't a ton of value in running every single type of build in the matrix then?

**Comment by clokep** [comment]
I'm not really sure what to do with this PR since it isn't clear to me that Celery officially supports these architectures. I don't see why they wouldn't, but have you contacted them? Is there an open issue or PR you can point me to?

For now I'm going to close this, but we can re-evaluate in the future.

**Pull request closed without merging**
